### ISSUE TITLE
🐛User tasks without title are skipped

### ISSUE THREAD

**Issue by dominikkaminski** [process-engine/process_engine_core#146]
#### Describe your issue

A user task without name will be skipped while processing.

#### How can others reproduce the issue?

Create a new diagram and add a user task without name.

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

**Comment by Vyperus** [comment]
@dominikkaminski Without a name or title? Which Field do you mean specifically?  
Otherwise I was not able to reproduce this on BPMN-Studio v4.2.0.
Please provide some insight in form of a diagram or something like this please :)

**Comment by ElRaptorus** [comment]
@dominikkaminski 
I couldn't reproduce this either. Please provide some info as to what kind of process diagram you used to reproduce this.

**Comment by dominikkaminski** [comment]
<img width="1440" alt="bildschirmfoto 2018-08-30 um 11 37 56" src="https://user-images.githubusercontent.com/27898950/44843824-88a67300-ac49-11e8-9f33-4939b882810e.png">

Still reproduceable in v4.2.0

@ElRaptorus @Vyperus 
Please leave user task **name** empty.

**Comment by ElRaptorus** [comment]
@dominikkaminski @Vyperus 
I don't know if this is even an issue any longer, but I can say with certainty, that the backend does not have a problem with managing unnamed user tasks.
We have tests in place that cover such cases.
