### ISSUE TITLE
📦 Improve Logging

### ISSUE THREAD

**Issue by robpal94** [process-engine/process_engine_core#196]
#### Describe your issue

We currently do not log that much on the Backend. Since we have the ability, to view logs in our frontend application, we should add more log messages, which are also less generic (If you view the log messages from different Correlations, you see that most of the messages are the same. For example, you only really see this kind of Messages on every Task in a given correlation: 
```
FlowNode Execution started 
FlowNode Execution finished
```

Maybe we could extend the logging a bit to make the log output a bit more *informative*.

### Add Informations to a FlowNode entered/exit state

Currently, for every entered FlowNode the above message is shown. But it does not testify that much. You can only see, that a FlowNode was entered and another left. But not really more. 

<img width="1412" alt="screenshot 2018-11-09 at 21 47 49" src="https://user-images.githubusercontent.com/38498731/48287444-382d6c00-e469-11e8-8183-d5771b908bba.png">

It would be _cool_ imo when the log actually shows, which FlowNode was entered to make it easier to follow the log. Something like

```
FlowNode ${Id} entered
...
FlowNode ${Id} finished execution
```

### FlowNode specific Log outputs: 

Maybe, the log can display some specialised informations for a dedicated FlowNode type. 

#### ServiceTasks

We should display more informations about the HTTP Query option of Service Tasks. For example the queried url and the http return code. 

```
Execution for FlowNode ${id} started
Query URL: ...
HTTP Result Code:  ...
...
```

Also for External Tasks, the whole log output of the ExternalTask should be passed through the Studio. 

#### ScriptTasks

As a User, I would expect that I can see the output that was produced by a ScriptTask in the LogViewer. This is currently not the case. 

The output of a ScriptTask, defined like this: 
```
console.log('Nobody wants to see me :('); `
```
is simply omitted. 

#### Events 

It would be helpful imo to see, which Events are thrown and received (especially Events that where received from other currently running ProcessInstances). 

Example: 
```
Process Execution started
Waiting for message 'My Message'...
Received Signal 'Unrelated Signal'
Received Message 'My Message'
Send Message 'Another Message'
....
```

IMO this would be a great help, when trying to debug Processes, which contains Events. 

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

## Example

<details>
<summary>
:warning: Before creating the issue, click here to expand and follow the guide.
</summary>
<br>
  
1. Be sure to fill out **every** topic presented in this template. 
If a section is not valid or useful for your issue, feel free to remove it.

2. Use the attached Checklist to make sure your issue contains all relevant information.

3. Attach a label to your issue that reflects what your issue is all about.
**When your issue concerns only a specific platform, be sure to attach the label for that platform!**

4. Please use a fitting emoji at the beginning of your issue title.

Example 1 - Report a bug:
```md
:bug: Something is not working properly
```

Example 2 - Report a performance issue:
```md
:zap: Something is slower than it should be
```

Example 3 - Report a package vulnerability or security issue:
```md
:lock: Package xy produces vulnerabilites
```

```md
:lock: User XY has access to something he shouldn't have
```

Example 4 - Report missing test coverage: 
```md
:white_check_mark: Add tests for...
```

You can of course phrase your titles however you like.
Just be sure they are short, to the point and convey the general idea of the issue you are experiencing.
</details>

## Emojis

<details>
<summary>
Expand for a list of most used Emojis.
</summary>
<br>

Please prefix your Issue with an Emoji.

Ref: https://gitmoji.carloscuesta.me/

| Description              | Glyphe               | Emoji  |
|--------------------------|----------------------|--------|
| Bugfix                   | `:bug:`              | 🐛     |
| Fixing Security Issues   | `:lock:`             | 🔒     |
| Configuration releated   | `:wrench:`           | 🔧     |
| Cosmetic                 | `:lipstick:`         | 💄     |
| Dependencies Downgrade   | `:arrow_down:`       | ⬇️     |
| Dependencies Upgrade     | `:arrow_up:`         | ⬆️     |
| Formatting               | `:art:`              | 🎨     |
| Improving Performance    | `:zap:`              | ⚡️     |
| Initial commit           | `:tada:`             | 🎉     |
| Linter                   | `:rotating_light:`   | 🚨     |
| Miscellaneous            | `:package:`          | 📦     |
| New Feature              | `:sparkles:`         | ✨     |
| Refactoring Code         | `:recycle:`          | ♻️     |
| Releasing / Version tags | `:bookmark:`         | 🔖     |
| Removing Stuff           | `:fire:`             | 🔥     |
| Tests                    | `:white_check_mark:` | ✅     |
| Work In Progress (WIP)   | `:construction:`     | 🚧     |

</details>

**Comment by cmg-dev** [comment]
Nice writeup. We will discuss this over the next month.

**Comment by ElRaptorus** [comment]
@robpal94 Good Summary. 👍 
For the LogView, you could alrady display things like the ProcessModelId and the FlowNodeId, as they are contained with each Entry.
See:
https://github.com/process-engine/logging_api_contracts/blob/develop/src/log_entry.ts

That was the reason why the messages themselves were kept so ... succinct.

But I think adding the FlowNodeId to the log message itself is not a bad idea.

/cc @cmg-dev

**Comment by ElRaptorus** [comment]
@robpal94 I think the backend logging was extended enough already. 

As for the log-viewer, I think it best if you just implement more columns that contain the properties you want to show. 
Or you could just customize the message yourself and add the relevant properties from the data model.

/cc @cmg-dev
