### ISSUE TITLE
♻️Refactor package name to process_engine_core

### ISSUE THREAD

**Issue by cmg-dev** [process-engine/process_engine_core#88]
#### Describe your issue

**DON'T DO THIS NOW**

The ProcessEngine is strangely cut into packages.

This package contains Core Function for the PE, but it is NOT a runnable ProcessEngine.

#### Possible solution

Use a different cut of the packages.

This packages is more like: process_engine_core;
and there needs to be a package: process_engine.

I expect the process_engine package to work like this:

```
npm install process_engine
(...)
# Functions shall be usable out of the box like:
process_engine import test.bpmn
```

Feel free to ask, what my vision about this is.

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

**Comment by ElRaptorus** [comment]
https://github.com/process-engine-pro/organization/issues/194

**Comment by cmg-dev** [comment]
This is still a thing.

currently the name is `process_engine_runtime`

I think this is also a good name. Still, I would like to fix the process_engine package to be called process_engine_core.

**Comment by ElRaptorus** [comment]
done.
The old releases for `@process-engine/process_engine` are still available through npm. Can't unpublish that package anyway.

The new ones will be published under `@process-engine/process_engine_core`, starting at version 1.0.0
